name: Test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16.14.2']

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run and test app
        run: |
          yarn install
          yarn build
          yarn lint
          yarn test:ci

#        env:
#          EXAMPLE_VAR:
